exception: move sd_bus_error_set calls to exception
In the future, generated exceptions will need to fill the sd_error
with something other than the "description" in order to pass more
metadata.  Move the sd_bus_error_set calls to exception as a virtual
function so this can be accomplished.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I6e6947e4977701a8e7e27fef119bd35e837d866b