server: object: reduce potential warnings
Some compilers and linters are not handling C++20 requirements
similarly and one, rightly, complains when the object class is
used that:

    object.hpp:198:34: error: parameter type '...' is an abstract class

An abstract class cannot be a variable or function parameter, but a
reference to one can be.  Switch the require statement to check a
`T&` instead of a `T` for the `emit_added` function calls.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Iaad189c37c4962193cfa94cd777e385686e5a9da