SdBusError: Add test cases
This adds basic unit testing to the SdBusError class so we have full
coverage of all the functionality.

Tested:
    Ran through the unit test suite including the changes that build
    valgrind runs and code coverage suppport.

Change-Id: I6d3bdbd2e0332ae5372796cb2a380ccddbee10ec
Signed-off-by: William A. Kennington III <wak@google.com>