exception: generate types for org.freedesktop.DBus.Error
The previous exception implementation used a generic SdBusError for
all cases where a function call to an sd-bus method gave an error.
This does not allow granularity so that different exception clauses
could be defined for different dbus errors, so it is not easily handled
(outside of manual string matching) to differentiate between, as
examples, a service not running vs a method call failure.

We already have a harness for generating exception types.  Leverage
that for "internal" errors generated by sdbusplus so that we can gain
finer-grained catch matching for various sd-bus errors.

Implement support for generated exception types for internal events,
mimicking the support already in place for generated_exceptions.  These
are required to inherit from an `internal_exception` type so that
existing try-catch clauses will still catch.

Change-Id: Ieb4f3b6832686734f5abeaffbd15d217613e74bf
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>