exception: fix use-after-free
ASAN testing revealed a likely use-after-free in the SdBusError class.
The class previously tried to take ownership of the sd_bus_error pointer
but the problem is that we cannot guarantee how far up the call-chain
the ownership of the pointer belongs.  With ASAN on a new test case, it
was observed that on the async-client path, the sd_bus_error was still
owned by the sd_bus_message object and was automatically cleaned when
the message was freed.  Later, an owner of the SdBusError attempting to
observe state like the `name` field would trigger a use-after-free.

Switch to use `sd_bus_error_copy` rather than simply moving pointers.
This ensures that the SdBusError has an explicit copy of all necessary
fields.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I501bb35f7e654f3f516e57ce853c657afdd56512