clang-tidy: remove unused private fields
Dropped unused members `fd` and `wd` from mutex.cpp to resolve
-Wunused-private-field errors under -Werror. No functional changes.

Fixed below errors.
'''
../test/async/mutex.cpp:94:9: error: private field 'fd' is not used [-Werror,-Wunused-private-field]
   94 |     int fd = -1;
      |         ^
../test/async/mutex.cpp:95:9: error: private field 'wd' is not used [-Werror,-Wunused-private-field]
   95 |     int wd = -1;
'''

Change-Id: If8079277c6e1be2760de8896997d7da4df6e1a98
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>