enums: fix ambiguous error in phosphor-logging
Various users failed with a strange phosphor-logging compile error
with the switch to concepts from SFINAE:

```
../subprojects/phosphor-logging/lib/include/phosphor-logging/lg2/conversion.hpp:419:50: error: call of overloaded ‘log_convert(const char*, lg2::details::log_flag<>, sdbusplus::common::xyz::openbmc_project::software::ApplyTime::RequestedApplyTimes&)’ is ambiguous
  419 |                                       log_convert(h.data(), log_flag<>{}, v)));
```

This is the result of phosphor-logging having a generic enum conversion
and an sdbusplus conversion that was not properly disambiguated.
Sprinkle around some decay_t to help disambiguate.  This helps ensure
that enum-references are properly matched.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I3d402ae9cd9c97e6e82eca6f1d9e089e79afbd82