message: handle vector<bool>
Attempting to create a vector of bools resulted in the following
compile error:
```
usr/include/sdbusplus/message/append.hpp:272:9: error: cannot bind non-const lvalue reference of type 'std::_Bit_reference&' to an rvalue of type 'std::_Bit_iterator::reference'
```

Most range-for operations for containers operate on a reference to the
value in the container, but `vector<bool>` has a "proxy" due to the
bit-wise optimization required by the standard.  Switching from `auto&`
to `auto&&` allows the proxy to be used (an r-value reference) while
also working for the non-proxy case (since `auto&&` will collapse to an
l-value reference).

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ic96a156f29fb9429529080f4319548d91ac0ce41