Revert "Fix incorrect defaultValue in generated server.hpp"
This reverts commit 14269fbcc15fd0e764f672de144d44e8ee26dd78.

This caused the following compile failure in phosphor-dbus-interfaces:
16:52:02 make[1]: Entering directory '/phosphor-dbus-interfaces-99b5aaa499c2f1a71a031051136744ad1e7df869'
16:52:02   CXX      libphosphor_dbus_la-libphosphor_dbus.lo
16:52:05 In file included from libphosphor_dbus.cpp:16151:0:
16:52:05 ./xyz/openbmc_project/User/Ldap/Config/server.hpp:195:53: error: expected unqualified-id before numeric constant
16:52:05          SearchScope _lDAPSearchScope = SearchScope::0;
16:52:05                                                      ^
16:52:05 make[1]: *** [libphosphor_dbus_la-libphosphor_dbus.lo] Error 1
16:52:08 make: *** [all] Error 2

Change-Id: Ie4c2f99d08b96845da86634ad73b9c8af56b656c
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>