sdbus++: async: handle zero parameter signals
Adding a zero parameter signal results in the following compile
failure:

```
../include/sdbusplus/message/types.hpp: In instantiation of ‘constexpr auto sdbusplus::message::types::type_id() [with Args = {}]’:
example/gen/net/poettering/Calculator/aserver.hpp:372:58: required from here
../include/sdbusplus/message/types.hpp:302:72: error: no matching function for call to ‘type_id_multiple<>()’
```

Fix this by reusing logic from the non-async code to special case
zero parameter length signals.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I0cde8810dfaf15afa2033a4c6699fb264facb9e8