exception: Add .code() method
Add the .code() method to provide the errno from SdBusError.
This is based on std::system_error::code, but a full
std::error_code struct is not needed to be returned, just the
value of the errno since SdBusError already provides methods
to get the error message and description.

Closes openbmc/sdbusplus#22

Tested: Added check for the new method to the exception
unit test suite. Also verified external callers get the right
errno value with:
    catch (const SdBusError& e)
    {
        int errno = e.code());
    }

Change-Id: Idddfa7f1bd9cfabfaf89e4d6c83146b4b9af211f
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>