exception: define 'internal_exception' class
internal_exception will be used for sdbusplus-generated errors.
These errors could be thrown by any sdbusplus call and therefore
by any generated server binding.  Define this class to differentiate
between binding-defined errors and sdbusplus-defined errors.

Change-Id: I725729c8e874b638cde8ce72289b87ed807d27c1
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>