async: fix reference initializer warning
Clang is unhappy about an initializer for a member reference, even
though the constructors properly initialize the value:

```
../include/sdbusplus/async/client.hpp:24:35: error: non-const lvalue reference to type 'sdbusplus::async::context' cannot bind to an initializer list temporary
```

Drop the `{}` so the member is uninitialized.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: If1f12e8eac4913f0147f39157dd9c48d1803bb9e