sdbus++: property: fix up enum type ambiguity
Adding a variant[enum[...]] to the test/server/Test.interface.yaml
yields a compile failure due to enumeration type ambiguity:

    builddir/test/server/Test/server.cpp:1022:47: error: ‘server’ is not a
    member of ‘sdbusplus::server::server’
            std::variant<std::string, server::server::Test::EnumOne,
            server::server::Test::EnumTwo>>());

Fix this ambiguity by properly adding the fully-qualified type name
in the type generation for enumerations.  ie. add the 'sdbusplus::'
prepending.

Tested: Compiled the test-change encountering the problem and the
full phosphor-dbus-interface repository with this change as a
subproject.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I186792c0a440711b1254489d8d066ef04c7732b8