clang-tidy:Fixed unused private field error
The following error was reported during clang-tidy enablement due to
the -Wunused-private-field warning.

Marked the variable as unused using the [[maybe_unused]] keyword.

'''
/include/sdbusplus/async/fdio.hpp:37:9: error: private field 'fd' is not used [-Werror
'''

Tested: Verified build and unit testing.

Change-Id: If99c7e55913a56e07b8de9a827c4dce0befc4c23
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>