sdbus++: fix method template generation
In the refactoring of the mako templates, a parameter was missed to
the `Method::returns_as_list` function.  This shows up as:

```
  File "method_prototype_hpp_mako", line 88, in render_body
  File "/usr/local/lib/python3.8/dist-packages/sdbusplus/method.py", line 36, in cpp_return_type
    self.returns_as_list() + \
TypeError: returns_as_list() missing 1 required positional argument: 'interface'
```

Add missing parameter.

Fixes d2fc8cc0b96b1861c647d00e1a9e5e98e9fc109e.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I35407ed1c4046d6eb232c883ec25938e4e4ab3d8