SdBusError: Really own the sd_bus_error
The sd_bus_error constructor claims to own the sd_bus_error pointer but
it doesn't prevent the user from trivially re-using it in a broken way.
Instead of accepting the argument by value, take the old value and
overwrite the caller's copy to NULL it out. This way future calls to
sd_bus_error_free() by the caller will do the right thing.

Change-Id: I0afd856f0a2a08a08f25fd43c051aae4b2a645f4
Signed-off-by: William A. Kennington III <wak@google.com>