SdBusError: Fix initialization checks
sd_bus_error_set_errno() is semantically useful in C for returning the
errno and constructing the error in a single call. However, since
successful population of the error can not be distinguished due to the
collapsed return value, we need another way to ensure the error was
built correctly. Don't check for the return of sd_bus_error_set_errno()
and instead use sd_bus_error_is_set().

Tested:
    Builds still work and tests still pass.

Change-Id: Ib7546d7bb19eb2ebbaf6e2cab79a8ecd8960f280
Signed-off-by: William A. Kennington III <wak@google.com>