exception: add event extensions
Add a mechanism to extend an event with any dbus interface.  This
allows customization of events for non-standard data such as: CPER
records[1], "hints"[2], or OEM extensions.

We currently prohibit two types of dbus interfaces from being an
extension:

    - Interfaces which have variants.
        - It is challenging to do automatic JSON serialization /
          deserialization of variant types so we are punting on this for
          now.

    - Interfaces which have methods.
        - Interfaces with methods may be "hiding" data inside the method
          calls which make it impossible to implement fully in another
          process.  Since the intention is for processes to be able to
          fully form a dbus interface implementation from the JSON we
          preclude that because it would require a custom implementation
          in the deserializing daemon.

Both of these constraints could be relaxed in the future if there is
need.

[1]: https://www.dmtf.org/sites/default/files/Redfish_LogEntry_for_CPER_WIP.pdf
[2]: https://github.com/openbmc/docs/blob/master/designs/event-logging.md#phosphor-logging

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Icc5b617459b799a0debb8e541c7befbb5c5aca13