exception: change org to xyz
The InvalidEnumString has a DBus identifier as org instead of
xyz.  Since our domain name is openbmc-project.xyz, this
should be xyz.openbmc_project.

Change-Id: I6d2a83d3ba8c5d39c6176aa6a12aae607eb08a8c
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>