utility: Fix type deduction for std::index_sequence
Upon running clang-tidy on a file in bmcweb I came across following
error message:

```
Error while processing /home/mox/openbmc/bmcweb/redfish-core/include/utils/eventlog_utils.hpp.
/usr/local/include/sdbusplus/utility/make_dbus_args_tuple.hpp:56:25:
error: no viable constructor or deduction guide for deduction of template arguments of 'std::index_sequence' [clang-diagnostic-error]
   56 |     std::index_sequence seq = std::make_index_sequence<new_size>{};
      |
```

Fix this by making the variable constexpr auto, since
std::index_sequence does not support class template argument deduction.

Tested: Code compiles. Clang-tidy on the aforementioned file is
satisfied.

Change-Id: Idf2e3b622eb2bd7f150fc6b638193b44640067d5
Signed-off-by: Oliver Brewka <oliver.brewka@9elements.com>